version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_invoke]
[default.local_invoke.parameters]